### ISSUE TITLE
Change licensing templates to use recommended format from REUSE v3.0

### ISSUE THREAD

**Issue by bernhardreiter** [greenbone/pontos#453]
Currently licensing headers have lines like (for Go):
```go
// Copyright (C) <year> <company>
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// This program is free software: you can redistribute it and/or modify
...
```

the current standard https://reuse.software/spec/ v3.0 suggests to use

```go
// SPDX-FileCopyrightText: <year> <company> <https://greenbone.net>
//
// SPDX-License-Identifier: AGPL-3.0-or-later
```

* [ ] Change from `Copyright (C)` to `SPDX-FileCopyrightText:` and add contact address. Fullfils the SHOULD in the reuse spec.
* [ ] Remove extra text `This program is ...` or at least reduce it. Saves space. Removes needs for updates.

Advantages: The rights holder(s) can be identified better automatically. The marking is kept flexible for the future.

**Comment by bernhardreiter** [comment]
https://github.com/Intevation/pontos/tree/update-headers-go-reuse30 does both for the AGPL Go template with https://github.com/greenbone/pontos/compare/main...Intevation:pontos:update-headers-go-reuse30 .

Note that the command must be called with a contact address, e.g. like
```bash
pontos-update-header --company 'Greenbone Networks GmbH <https://greenbone.net>' -l AGPL-3.0-or-later -d cmd/
```

**Comment by bjoernricks** [comment]
Could you create a PR and we also need a possibility to update and keep existing headers.

**Comment by bernhardreiter** [comment]
@bjoernricks would you accept a PR that only updates AGPL and go?

**Comment by bjoernricks** [comment]
We need this tool for updating the copyright in many repos and files. As long it stays backwards compatible or has an upgrade path and there are unit tests I am fine with every PR.
